### ISSUE TITLE
Use of Delete button to remove elements in visual editor

### ISSUE THREAD

**Issue by lexvand** [nens/lizard-management-client#1005]
You can only remove elements by selecting them and press Backspace. To me it seems more intuitive to use the Delete button. Is there a reason why that doesn't work?

**Comment by hoanphungt** [comment]
The default option is using the `Backspace`. I can change it to `Delete`. I think it makes sense, also takes me a while to figure out to use `backspace` to delete an element. Would be best to be able to use both options. I will have a look at.

**Comment by hoanphungt** [comment]
Current version of the react-flow library only allows to use one key code for elements. I chose to use `Delete` instead of `Backspace` for the deletion. In near future, it will become possible to use multiple key codes for the deletion as it is currently being worked on in this issue: https://github.com/wbkd/react-flow/issues/1370

**Comment by lexvand** [comment]
Works more intuitive now. Let's keep the option for the Backspace in the back of our mind for later. May not really be necessary.
