### ISSUE TITLE
Link from geoblock build modal to lizard catalogue or lizard client

### ISSUE THREAD

**Issue by hoanphungt** [nens/lizard-management-client#1022]
During the demo by Joep, it is noticeable that Joep needs to switch between the lizard management, lizard catalogue and the lizrd viewer a lot in order to see the changes made to a geoblock. In the 2nd iteration, we'd like to build a preview tab to quickly view the changes. However, for the short term, probably a button/link to open the current geoblock in the Lizard Catalogue or directly open it in the map in the Lizard Viewer would greatly improve user experience with the geoblock build modal.

**Comment by hoanphungt** [comment]
@JoepGrispen @lexvand 
I made this ticket for the geoblock build modal based on the demo by Joep for the IT department.

**Comment by JoepGrispen** [comment]
part of the switching and lack of a nice flow was also due to the surprise of the result. I changed and saved the geoblock in a previous demo. I noticed it during the demo for the team hence the disruption in the flow and demo. Nevertheless due recognize that the short term solution would improve the workflow a lot

**Comment by lexvand** [comment]
Works.
