### ISSUE TITLE
Raster - Form

### ISSUE THREAD

**Issue by Derryrover** [nens/lizard-management-client#455]
Design ticket for new raster management client: https://github.com/nens/lizard-management-client/issues/237 (contain links to different designs including raster form)

Be noted that there are now raster sources and raster layers. So there will be 2 different forms for them respectively.

The 1st step is to create a raster source and then to create a raster layer. A raster layer must belong to 1 raster source. Raster source must have at least 1 raster layer.

** TO DO: 

- [x] Check form fields made by Remco if they can be reusable --> make new React components for the fields
- [x] Make react custom hook to reuse logics for form
- [x] Make React components for fields
- [x] Color map input component
- [x] Make Raster source form
- [x] Make Raster layer form
- [x] Make popup modal to transit from raster source form to raster layer form and connect them together (might need to add raster source uuid to Redux store)

No styling is done yet.

**Comment by hoanphungt** [comment]
@Derryrover 
Hi Tom,

The PR for this issue is ready for review: https://github.com/nens/lizard-management-client/issues/490. However, I think it's too large to review at this point and we can also go through them together on Monday (together with the table):

Be noticed that the many components under the `form` folder for different fields of the form don't need to be reviewed as they have already been reviewed in the ticket for form technology: https://github.com/nens/lizard-management-client/issues/240. There are also some other components made in this folder but they are copied from Remco's ones with some small tweaks.

Also, I still expect to change things to make it more stable (i.e. the field components). The error handling when creating/updating rasters has not been included yet.

Kr, Hoan

**Comment by Derryrover** [comment]
@hoanphungt 
Excellent 
We will look together monday.
Have a good weekend!

**Comment by Derryrover** [comment]
Code and functionality looks good!
I think it is okey to merge to feature branch, or wait for your styling branch to finish.
