### ISSUE TITLE
When uploading temporal rasters, make clear that time is in UTC

### ISSUE THREAD

**Issue by LirryPinter** [nens/lizard-management-client#460]
@caspervdw made clear that users need to upload their temporal rasters in UTC time (so that timezones aren't an issue). 

2 actions are needed:

- Make users understand they are filling in an UTC time instead of local
- Change the date time picker to UTC

**Comment by LirryPinter** [comment]
@Derryrover @caspervdw 

I transfered it to the correct repo, sharp! 

I know the time is send as UTC to the backend, but the users would have to know that and calculate the difference. 
The user should enter their time in a time/date picker that is showing UTC, because else they would have to calculate every time they want to upload a temporal raster. @caspervdw and an advisor had problems with this last time they  did that.  Most users take the UTC as an international standard voor rasters.

Isn't that possible with momentJS?

**Comment by LirryPinter** [comment]
@Derryrover 

What we can do is leave the field empty when the user fills it in, so that they aren't confused with local time. I already put the title of "Date/time (UTC)" above the field in the design. Then the picker shouldnt convert but just post the UTC time to the backend.

How does that sound?

**Comment by Derryrover** [comment]
The problem we will try to solve is that:

- Some users prefer to enter time in UTC, but this is now not possible
- It is unclear if the current time entered is utc or local (it is local unless automatically parsed from the filename, see next point)
- There is a nasty bug/feature in the current app that if the date is parsed from the filename then it is shown in the datepicker in UTC, but when user fills out datepicker or default date is used then it shows in datepicker as local time

A solution should involve:
- clearity if time choosen is utc or local
- option to choose in both utc and local
- clear behaviour what happens when date parsed from filename

Possible solutions include:
- let user choose between local or utc time in a dropdown for datepicker
- show user 2 date pickers: one local, one utc. Keep in sync. ( I prefers this one)
- Keep datepicker in local time but show readonly utc time next to it. (possible problem with moving clock one hour back time)

**Comment by lexvand** [comment]
No longer relevant. Timestamp is read from filename.
