### ISSUE TITLE
Timeseries management

### ISSUE THREAD

**Issue by lexvand** [nens/lizard-management-client#461]
Design:
https://xd.adobe.com/view/64bdf742-fee5-4907-a0f1-e9f27ecac3fc-31ee/

**Comment by Derryrover** [comment]
@lexvand 
@LirryPinter 

Hi Lex and Lirry,

I am planning to make subtickets for the timeseries management.
I am having some trouble finding the relevant design tickets and adobe links.
Am I missing something?

Could you help me out?
Thanks in advance!

kr Tom

**Comment by LirryPinter** [comment]
@Derryrover 

Hi Tom,

Still working on the modal to add timeseries to monitoring networks, the complete design I can put in the description of this ticket. 

Normally look for my tickets and maybe add a reaction to ask if that is the correct design because I do not have the same epics as you guys :)

**Comment by LirryPinter** [comment]
Icons for the tiles 

![Group 351.png](https://images.zenhubusercontent.com/5edf4fb3573d27e45d88f233/b5b71dbd-b345-4e29-8ca2-325dfe42cc3b)![Group 352.png](https://images.zenhubusercontent.com/5edf4fb3573d27e45d88f233/535bc0ec-ebd0-4787-a34e-f9898f2369fb)

**Comment by LirryPinter** [comment]
@Derryrover @lexvand @hoanphungt 

Feedback and changes to design:

- New item button for timeseries and monitoring network tables --> **In design**
- Interval field --> option for irregular interval (interval = 0) --> **DESCISION: Default of field is now 00 00 00 00, so that means irregular interval. will need a good explanation in the explanation box**
- Leave out data field in timeseries form --> **In design**
- Make supplier/supplier_code fields not read-only --> **In the design this was for suppliers, so this was intentional. When logged in as an admin these fields are editable, like in all other management screens.**
-What does the actions button do in all three forms? --> **Delete for now, we could add the actions from the list view (like change obs type and then automatically select the obs type field)**
- Modal for location form - select related asset --> set location geometry based on asset geometry --> **In design, but no modal. Similar to alarm management**
- Removed supplier code from location --> **In design**
- Modal for adding timeseries to monitoring networks --> **In design**
