### ISSUE TITLE
Geoblocks management

### ISSUE THREAD

**Issue by lexvand** [nens/lizard-management-client#485]
Design link: https://xd.adobe.com/view/d2ef027c-c01f-45e7-9bac-c871f4bcdbf4-87bc/

**Comment by Derryrover** [comment]
@hoanphungt 
@lexvand 
@joeriverheijden 

Hi Hoan, Lex, Joeri,

I am not so convinced about the exact layout of the current adobe design.
I drafted an alternative design above.
I think we should also seriously consider the preview functionality since this also makes clear what exactly the geoblock does.
Any questions opinions and improvements are welcome!

kr Tom
