### ISSUE TITLE
Styling of form

### ISSUE THREAD

**Issue by hoanphungt** [nens/lizard-management-client#488]

**Comment by LirryPinter** [comment]
@hoanphungt 

Looks great! Some small feedback:

- The dropdown fields should have an arrow down when nothing is selected yet, not a cross.
- The text that is filled in should be darker, now it looks a lot like the placeholder
- I see that the whole page is scrollable, in the design it was different (lets have a meeting, about this because i have a better idea i think)
- Not sure if this should be in this ticket, but the colors of the header and text are not like in the design
- Lets make the lines that show that something is selected a bit thicker, now its not completely visible.
- If a form is completed, the user should get a notification (lets discuss this in the same meeting)
- Its super nice that we can navigate with the tab now! Only point is that when we navigate to a dropdown, it doesn't work. Lets fix that!
