### ISSUE TITLE
Design WMS Management 2020

### ISSUE THREAD

**Issue by LirryPinter** [nens/lizard-management-client#500]
Design ticket for WMS layers, will contain a link to the design.

Design link:
https://xd.adobe.com/view/6b896857-3a85-4665-9f7e-5151b4a73df0-3eda/

**Comment by Derryrover** [comment]
@LirryPinter 

Hi Lirry,

Since the work for management-rasters is almost finalizing, I am considering proceeding with wms.
Is there a design for the form (or maybe just a wireframe) ?
Currently I do have a design for the list, but not sure if outdated:
https://xd.adobe.com/view/113cd145-2091-4d91-45c9-198c4b05f5bd-670d/screen/222438cc-ff72-4f04-bf03-db628895f9f6/

Also a draft of the list is already on staging (using the new list component):
https://nxt3.staging.lizard.net/management/#/data_management/wms_layers

If the design is not yet finished no problem, then I can pick up another ticket.

kr Tom

**Comment by LirryPinter** [comment]
@Derryrover 

I have put the correct design link in the description.

For now its pretty low level.
Some considerations:

- What are the most important field to look at in the form?
- What are the bulkactions available for a wms layer (probably only delete)

**Comment by LirryPinter** [comment]
For the form:

General

Name (optional)
Description (optional)
Datasets (maybe same field as shared with)

Data:
Spatial bounds (4 fields next to eachother)
WMS Url (text field)
Get feature info (checkbox)  Get feature info url (text field)
Download url (text field)
Legend url (text field)
Tiled (checkbox)
Min and max zoom (two dropdowns)
Options (open field)

Rights
Organisation (required, but taken from user log in)
Access modifier (standard on private)
Shared with (optional)
Supplier (required, but taken from user log in)

**Comment by LirryPinter** [comment]
Get Feature Url boolean together with textfield (so if its filled in, set to true, if not set to false)

**Comment by LirryPinter** [comment]
Updated design link:

@hoanphungt 

I made the form for the WMS layer, lets plan a short meeting for reviewing the workflow!

**Comment by LirryPinter** [comment]
* What is download url ?
* What is tiled?

* Check possibilities for feedback/previewing data (map?)

**Comment by Derryrover** [comment]
@LirryPinter 

Hi Lirry,

Please have a look at how the "shared_with" checkbox works if a raster layer has shared_with organisations is later unchecked and then saved:
https://nxt3.staging.lizard.net/management/#/data_management/raster_layers/d7de6aff-7aa5-4ec1-b6ed-1079dfa690e3/

Is this as designed? or should the shared with sluchbucket become empty when the checkbox is unchecked?

I am not convinced, because the checkbox seems to be used to toggle visibility, but wouldnot a collapse arrow be more suitable?

kr Tom

**Comment by LirryPinter** [comment]
@Derryrover 

Hi Tom,

I took a look, and I understand the question. Firstly, it needs to be 'share with other organisations' like in the design. 

When this is unchecked, it is correct to remember the choices, because this can be useful if they accidentally click this checkbox while selecting organisations. 

The checkbox does not toggle visibility for the user, but simply the question if they want to share their data with other organisations. Therefor this is better then a collapse arrow. Also, nowhere in the design is a collapse arrow, and the goal to save space when users are not interested in sharing with organisations is reached by using the checkbox.  

I hope this clears it up for you
