### ISSUE TITLE
Improve raster form

### ISSUE THREAD

**Issue by hoanphungt** [nens/lizard-management-client#501]
Design: https://github.com/nens/lizard-management-client/issues/237

TO DO: 

- [x] Improve raster modal
- [x] Improve event handlers in useForm hook
- [x] Remove remembered scroll bar position
- [x] Remove @ts-ignore
- [x] Raster source selection field
- [x] Validator for color map input component
- [x] Fix color map input component
- [x] Fix x in dataset dropdown
- [x] Set focus on select box and slush bucket when using tab

**Comment by hoanphungt** [comment]
@Derryrover 
Hi Tom

Could you review this specific commit: https://github.com/nens/lizard-management-client/pull/508/commits/6fb1a6258222bdff5c448dc83cc643b7f1fd93ac? In this commit, I added the dropdown for the list of raster sources in the raster layer form. I used useEffect to fetch the list of raster sources and keep it in React state of the component.

Kr, Hoan

**Comment by Derryrover** [comment]
@hoanphungt 
Hi Hoan,
Looks good you can merge.
The only real concern is the page_size=10000
But in order to fix this we need a better approach for the selectbox ticket and you already made a new ticket for that here: https://github.com/nens/lizard-management-client/issues/518
So that is all good
kr Tom

**Comment by hoanphungt** [comment]
Merged!

Tom's concern with the query `?page_size=100000` for list of raster sources in the raster layer form is well-noted.
