### ISSUE TITLE
Improve raster form part 2

### ISSUE THREAD

**Issue by hoanphungt** [nens/lizard-management-client#507]
After meeting with Lirry, some more issues with the form is discussed as follows:

- [x] Form is still scrollable but with sticky explain column on the left side bar
- [x] Notification when form is submitted (whether successfully or not) using a snackbar like in the live-site (design: https://xd.adobe.com/view/c69b4792-e778-401c-982d-5c57caedf761-93c8/screen/a76d2f29-8099-4428-aff6-87a047347547/specs/)

**Comment by hoanphungt** [comment]
@LirryPinter 
Can you include the link to the design of the notification bar that you showed me in the new scenario management?

@Derryrover 
Hi Tom, Lirry showed me the design of a notification bar to notify users when submitting the form (quite similar to the snack bar in the live-site). Do you expect to also use them in other places like the raster table (for deleting/flusing raster) ...? What do you think about it?

**Comment by Derryrover** [comment]
@hoanphungt 
@LirryPinter 

Yes eventually we will use them also on tables and other forms or maybe even the queue.
I think it is a good idea.
I could not yet find the design of the snackbar.
I also think that the snackbar might be a last resort to notify the user if this is otherwise not satisfactory possible within the normal ui.

**Comment by hoanphungt** [comment]
@lexvand 
Is it ok to add this one to the current sprint? There are 2 main points that require extra work for the form as listed in the description. Some other smaller issues I added to the current one in the sprint.

**Comment by hoanphungt** [comment]
@Derryrover 
Hi Tom,

Would you have time to review this PR: https://github.com/nens/lizard-management-client/pull/513?

I added the scrollbar successfully by adding `overflowY: auto` in the child component of the ExpalinSideColumn.tsx component instead of directly adding the scrollbar in the Form component.

The snackbar design I got it from this one: https://xd.adobe.com/view/c69b4792-e778-401c-982d-5c57caedf761-93c8/screen/a76d2f29-8099-4428-aff6-87a047347547/specs/. I kept the dismiss button as it is still useful sometimes.

Kr, Hoan

**Comment by Derryrover** [comment]
@hoanphungt 

Hi Hoan,

I think the code looks good.

Functionally I think the snackbar at the end of creating a new raster-source might not be needed, because a modal is already opened.
The snackbar after raster-layer is good.

The scrollbar:
The raster-layer form there is still an additional vertical scroll over the whole page that should not be there. 
Also a tiny bit of horizontal scroll is on the raster-layer form (but only in firefox, so we may accept this for now). 
Maybe still quite a hell of a job to fix these darn scrollbars. 

Maybe you also can add some whitespace: 
- between the scrollbar right of the form and the content of the form.
- the whitespace between the header and form content does in the design of Lirry not scroll. This creates a calmer effect. Maybe also try to add that.
The reason I am now nitpicking over whitespace and stuff is because I feel the form now makes quite an uncalm impression on me.
Not sure if this whitespace will fix this, but overall I liked the form better when with the scroll on the whole page, not sure.
Maybe talk with Lirry.

kr Tom

**Comment by hoanphungt** [comment]
@Derryrover 
Hi Tom,

Thanks for your review and comments. It makes sense. I made some new commits to:

- Remove notification in the snackbar when create a new raster source
- Add more white space to the right of the form and the top of the form to make the scrolling smoother and calmer. It looks better with these whitespaces.

And you are right, I didn't notice that there is still other vertical + horizontal scrollbars in the raster layer form. I found this vertical scrollbar very strange and still couldn't fix it. It's strange because both the raster layer form and raster source form using the same format and styling but they behave differently. Would you mind to look at this with me on Monday's morning? Otherwise, you can suggest another time that is suitable for you.

I will merge the PR into the feature branch for now.

Kr, Hoan
