### ISSUE TITLE
Table action buttons

### ISSUE THREAD

**Issue by Derryrover** [nens/lizard-management-client#509]
Possibly improve styling table action buttons.
Currently we use a select with options html element.
There is only limited styling available.

If we want to improve the styling we can look for a component based approach.

**Comment by Derryrover** [comment]
@LirryPinter 
Hi Lirry,

For your information:

This ticket is for the table-action-buttons styling. In order to style this we need to make a component of it.

I choose not to implement this yet as a component, but use standard html component instead.
Standard html css is faster to develop and maintain.

Anyway, we will soon do a staging release and you may evaluate how important this ticket is.

kr tom

**Comment by hoanphungt** [comment]
@Derryrover 
Hi Tom,

Could you review PR: https://github.com/nens/lizard-management-client/pull/638/? I need to make sort of a workaround for the last action button in the table to render a drop-up instead of a drop-down (but not if there is only one row in the table, for example the API key table). Otherwise, the dropdown will cause a scrollbar and you need to scroll down to see the actions. I think this is not ideal but can't think of other solution right now. If you have any suggestion/idea for improvement then please do not hesitate to try it out.

Kr, Hoan

**Comment by Derryrover** [comment]
@hoanphungt 

Approved, ready to merge!
That the last item in the table opens upwards works well!
Let us merge and see what Lirry thinks.

kr Tom

**Comment by lexvand** [comment]
Nice styling improvement. Drop-up indeed works for last item.

The only case in which the options menu falls behind the edges of the tabel is when you increase the page size, introducing a scroll bar. The drop-up effect is not applied for the last item in sight. Is that something we can easily include in the exception handling, @hoanphungt? If not, we leave it for now.
![image](https://user-images.githubusercontent.com/5370809/107652311-bd271180-6c80-11eb-857e-167fccbf8aca.png)

**Comment by hoanphungt** [comment]
@lexvand 
It doesn't look straightforward to handle these exceptions, there will be too many of them as you scroll down. The idea is only the last item will have the drop-up so it will not cause extra scrollbar. The best solution for all of this is to have the dropdown always on visible in any cases then we don't have to handle exception but I can't find a way to do it for now. I will create a separate ticket for it.

**Comment by hoanphungt** [comment]
Created separate issue: https://github.com/nens/lizard-management-client/issues/660

**Comment by lexvand** [comment]
Already thought it would be difficult. Closing this issue as it works good enough.
