### ISSUE TITLE
New source raster continue redirect goes to empty page

### ISSUE THREAD

**Issue by Derryrover** [nens/lizard-management-client#548]

**Comment by Derryrover** [comment]
merged without review

**Comment by GeOdin** [comment]
@Derryrover 
Hey Tom :)

Do I understand this correctly:
Previously you would be redirected to an empty page after pressing the '+ new item' button on the raster source management page.
https://nxt3.staging.lizard.net/management/#/data_management/rasters/sources

Now, if you press the '+ new item' button of the raster source management page, you go to the raster source creation page.
So that works nicely.

Let me know if I misunderstood this ticket.

Kind regards,
Madeleine

**Comment by Derryrover** [comment]
@GeOdin 

Hi Madeleine,
Excuses, the description is indeed missing.

The bug was that if you create a new raster you are supposed to get redirected to a new layer form.
This suppose to happen after a modal with a "continue" button.
The bug is that if you click the "continue" button in the modal, you did not get redirected to a new raster-layer-form, but to a empty screen instead.

Also have a look how it works in the design of Lirry here:
https://xd.adobe.com/view/80bc79b4-fbd2-4d42-9d7f-00b84d2e89c3-d5ef/screen/895bee74-cf49-4fa5-92bd-4b05615d1d16

kr Tom

**Comment by GeOdin** [comment]
@Derryrover 

Thank you Tom. :)
I will have another look at it.

Kind regards,
Madeleine

**Comment by GeOdin** [comment]
Hey Tom :)

Thank you for the explanation.
I tested it with your information and it works nicely! :)

Kind regards,
Madeleine
