### ISSUE TITLE
Improve situation with dropdown fields in forms

### ISSUE THREAD

**Issue by Derryrover** [nens/lizard-management-client#614]
For the forms we are currently using custom build dropdown fields.
For example for raster-layer:
- observation type
- colormap
- source
- agregation-type
The above 4 fields are all using the "SelectBox.tsx" component to display the custom build dropdown field.

We also  use standard HTML select/option element for the action buttons in the table and form.

What we need is one (or multiple?) well implemented dropdown fields.

The current dropdow fields are:
- buggy
- slow / unreponsive
- fall over and under each other
- can not show icons (in case of the standard html dropdown)

Some requirements for the new dropdown field:
- Support cases: a simple select dropdown, a select dropdown with search bar, a select dropdown under a button (e.g. "Action button")
- More responsive
- Cannot overlap each other (one will be closed if a new one is selected)
- May/may not support search bar depends on the amount of data to search from
- May/may not support to make API calls based on search input

Creating a storybook to demo the new dropdown field is a good idea.

**Comment by hoanphungt** [comment]
@Derryrover 
I am investigating the use of 'react-select' library for different types of dropdowns: https://github.com/JedWatson/react-select. Demo: https://react-select.com/home

**Comment by hoanphungt** [comment]
@Derryrover 
Hi Tom,

Could you review this PR: https://github.com/nens/lizard-management-client/issues/628? I used the 'react-select' library for the dropdown. Two disadvantages of using this library are:

- They accept value as an object instead of a string: `{value: string | number, label: string}` so I need to convert the value to object anywhere I use the `SelectDropdown` component

- CSS styling is done differently than the rest of the form as this requires to use their own styling API instead of using class names. Styling can be done using class names but it's not the preferred way.

I used the `SelectDropdown` component for the raster source, raster layer and wms layer forms.

Kr, Hoan

**Comment by Derryrover** [comment]
@hoanphungt 

Hi Hoan,

Looks good!
You can merge.

I see you also added some css variables. Very good

kr Tom

**Comment by lexvand** [comment]
Works excellent. Nice distinction between single and multi selection fields. Filtering works good. Related issues are also resolved.
