### ISSUE TITLE
Timeseries alarm - Form

### ISSUE THREAD

**Issue by Derryrover** [nens/lizard-management-client#647]

**Comment by Derryrover** [comment]
@LirryPinter 
Hi Lirry,

Not sure if this design is finished.
Is this the correct finished design?
https://xd.adobe.com/view/63185198-afa0-4a27-9d61-dc0395753bf9-364b/screen/cd83f207-0fb0-4c9e-827b-5138d0fb4cd3/

kr Tom

**Comment by hoanphungt** [comment]
@Derryrover 
Hi Tom,

Since both the raster alarm form and the timeseries alarm form are pretty much similar to each other (except from the source selection field). I will pick up this ticket later when the raster alarm form is finished. I see that the board is also quite empty now, so please let me know if you prefer another way of doing it.

Kr, Hoan

**Comment by Derryrover** [comment]
@hoanphungt 

Hi Hoan,

Approved and ready to merge!
- timeseriesSelect component looks good
- nice that you could remove so many old code

kr Tom
