### ISSUE TITLE
Reduce page_size in request for raster sources when creating a new item in the layer form

### ISSUE THREAD

**Issue by lexvand** [nens/lizard-management-client#659]
Page size is currently set to 10,000. This is undesirable from a performance point of view and with the search option it should no longer be necessary.

Or am I missing something here that would break the user workflow?

**Comment by hoanphungt** [comment]
@lexvand 
Currently, when creating a new layer, the raster source field is just a normal search input, not an async search dropdown like the observation types. That's why it needs to fetch all the raster sources beforehand. I think making it also an async search dropdown is a good idea. I will try it out. Probably gonna be quick.

**Comment by lexvand** [comment]
Nice! Works just fine.
