### ISSUE TITLE
Linking to page within management screens sometimes leads to white page

### ISSUE THREAD

**Issue by lexvand** [nens/lizard-management-client#680]
For instance: https://hhnk.lizard.net/management/#/data_management/scenarios/

![image.png](https://images.zenhubusercontent.com/5ede3192cc5c2c4503d452e7/4a8dd53b-fe06-440f-87e2-b46a285994db)

Refresh (both F5 and hard refresh) does not help. It doesn't request for the user roles, hence the error in the console. I guess the internal authorisation method doesn't work correctly. Navigating from the main management to the same location does work.

EDIT: Could also be that something goes wrong with redirecting to the login page when the user is not logged in. Tom suggests that it is caused by error: TypeError: this.props.selectedOrganisation is null

**Testing**
This bug is 100% reproducable by going directly to the following url in a new incognitio window:
https://nxt3.staging.lizard.net/management/#/data_management/scenarios
https://hhnk.lizard.net/management/#/data_management/scenarios/
Do not login first or go to the main page first.
The bug is that these wil show a blank page.
The desired behaviour is that they will redirect to the login page.

**Comment by lexvand** [comment]
@lisannewapstra Eerdere issue stond in verkeerde repo.

**Comment by Derryrover** [comment]
wip pr
https://github.com/nens/lizard-management-client/pull/681

**Comment by hoanphungt** [comment]
@Derryrover 
Code looks good. However, in dev, I experienced some strange things:

1. I can start the app using `yarn start` without having to provide `PROXY_USERNAME` and `PROXY_PASSWORD`. However, the app still used my login details for bootstrap.
2. If I open the page in incognito mode, using `yarn start` leads me to the login page. After login, I am redirected to the lizard portal and I cannot go to the management page anymore (going to `localhost:3000` or `http://localhost:3000/management#/` always redirected to the lizard portal). 

I am not sure if these problem will still happen if we go to staging.

Kr, Hoan

**Comment by Derryrover** [comment]
@hoanphungt 

Hi Hoan Thanks for the review
I merged this.
The problem you describe is known to me.
I think we have the following situation:

- If you not supply username password, the browser assign the authentication cooky / token to the url of staging somehow so the backend still thinks we are logged in. I am not sure why the browser assigns this auth cookie / token, because the domain is different (localhost vs nxt3.staging.lizarn.net).
Anyway, I think this is a problem on dev not on staging. Let us see what happens on staging.
- If you do not supply username pasword in incognito browser the auth cookie / token is not there so backend redirects you to the amazon sso. We tell the sso to redirect to localhost, but this is probably not whitelisted by the amazon sso and therefore we get redirected to the default page nxt3.staging.lizard.net. Also I think not a problem on staging and prod.

This is how I think it works. Let us pray it works on staging ;)

kr Tom

**Comment by lexvand** [comment]
@Derryrover On staging it now indeed redirects to the login page. When returning in the management client you are in the main page. Is this the right behavior or should you end up in `/#/data_management/scenarios/`?

Anyway, this can go to production.

**Comment by Derryrover** [comment]
> @Derryrover On staging it now indeed redirects to the login page. When returning in the management client you are in the main page. Is this the right behavior or should you end up in `/#/data_management/scenarios/`?
> 
> Anyway, this can go to production.

Good finding. I think we should end up in the scenario page (ideally).
The "next" parameter to the sso specifies the complete url including "/#/data_management/scenarios/".
Maybe frontend is passing this parameter incorrectly. Currently we are passing:

https://nxt3.staging.lizard.net/auth/login/?domain=&next=https://nxt3.staging.lizard.net/management/#/data_management/scenarios

As you can see the domain is empty.

Continue here:
https://github.com/nens/lizard-management-client/issues/707

**Comment by Derryrover** [comment]
@lexvand 

Hi Lex,

Er zit ook een refactoring van routing in deze versie.
Hoe uitbundig is er geprobeerd door alle tiles / schermen / formulieren heen te klikken tijdens testen?

Andere optie is dat we gewoon reverten als er een bug uitkomt.

groet Tom
