### ISSUE TITLE
Scenario raster layer management

### ISSUE THREAD

**Issue by lexvand** [nens/lizard-management-client#689]
We want to make raster layers of scenarios manageable apart from the non-scenario layers. This will mainly be used to change the colormap or the observation_type. Therefore we should make a copy of the raster layer management screen underneath the scenario management.

Differences in the implementation of this copy:
- Invert scenario__isnull filtering.
- In the table the button for "New item" should be removed.
- No delete actions, both in table and in form (would conflict with the deletion of results, so should be done in scenario management)

The form should have the same writable and read-only fields. We may choose to make the source field manageable for non-scenario layers later on, especially when we introduce Geoblock management, but for scenarios the user should not be able to change how the postprocessing constructed the setup.

**Comment by joeriverheijden** [comment]
@lexvand @Derryrover Let's make sure that @LirryPinter thinks of the design layout.

**Comment by joeriverheijden** [comment]
@lisannewapstra kan jij de Topdeskmelding van Wayne & Anne hieraan koppelen?

**Comment by lisannewapstra** [comment]
2102 0217 Anne Lesken & 2102 0180 Wayne

**Comment by Derryrover** [comment]
@lexvand 
@joeriverheijden 
@LirryPinter 

In addition to (or instead of) showing _"a copy of the raster layer management screen underneath the scenario management"_ we may:
- Put the default filter scenario=null on raster-layers behind a checkbox. (How it was previously done actually)
- Add also a 'filter/search on scenario' in list of raster-layers.
This may be small changes that can also solve the immediate issue.

Further showing _"a copy of the raster layer management screen underneath the scenario management"_  could be done using a related-list.
Related lists are powerful gui structures to clearify relations between objects.
Another ticket now on the backlog that could benfit from a related list (as also seen under option3 of my comment in that ticket):
- Change authorization of scenario + related rasters
https://github.com/nens/lizard-management-client/issues/690

kr Tom

**Comment by lexvand** [comment]
We discussed this earlier and we explicitly want to split this from the management of "normal" rasters and thus not reintroduce the checkbox. This helps to make it more clear to the users. 

The related lists may be an interesting option here (I think it is less applicable to #690). We already have the list of results. We can change the raster results into links to the specific raster layer object (raster__uuid can be retrieved from the raster_url in the results response). 

@LirryPinter What do you think of this? We need to pay attention to the breadcrumb navigation and how to redirect the user back to the scenario after saving changes.

**Comment by joeriverheijden** [comment]
Yes. It's really important that it's within the 3di scenario management page instead of the raster layer page. 3Di scenario's should be regarded as a different entity than raster layers. Although they contain raster layers, it's a different thing for the user where all results are regarded as one set of simulation results.

**Comment by Derryrover** [comment]
@joeriverheijden 
@lexvand 

Okey Joeri and Lex
Let's regard scenario-raster-layers as separate entities from 'normal' raster-layers.

Have to say I personally do not prefer this approach because:
- It hides domain-logic. Bad for the power-user that actually understands our data-model.
- It is more work to deliver "value to the business". If we would not have made the scenario=null filter mandatory we would not even have these tickets from Anne and Wayne.

**Comment by LirryPinter** [comment]
@lexvand @Derryrover @joeriverheijden 

I agree to this method! Looks simple and clear. 

Im gonna add it to the 3Di management design

**Comment by Derryrover** [comment]
Added to blocked in sprint, because there is no design yet

**Comment by Derryrover** [comment]
WIP:
https://github.com/nens/lizard-management-client/pull/703

**Comment by Derryrover** [comment]
@lexvand 
@byrman 
Hi Lex and Carsten,

question: How do I know if a raster-layer belongs to a scenario?

For raster layers belonging to a scenario some fields in the management form need to be read only.
How do I know if a raster-layer belongs to a scenario?
I have 2 options

1. Frontend logic: pass url parameters. The user always arrives at a raster layer form belonging to a scenario via the scenario form. I can pass along a url parameter to indicate that the user just came from the scenario form. I do not really like this approach, because the user can manually remove these url parameters and also maybe lateron the user can also reach the raster layer in another way.
2. Api logic. Something in the api indicates that the raster layer is belonging to a scenario. The only one I can find right now on raster layer is wms-info layer contains the word 'scenario:
"wms_info": {
        "endpoint": "https://nxt3.staging.lizard.net/wms/",
        "layer": "scenarios:1249:indirect-damage"
    },
https://nxt3.staging.lizard.net/api/v4/rasters/a5a6ed5a-e6c5-4097-9524-11fd4698dc70/
Is this a reliable way? It also feels shaky. Which other ways do I have?

kr Tom

**Comment by Derryrover** [comment]
merged without review:
https://github.com/nens/lizard-management-client/pull/703

**Comment by lexvand** [comment]
Just discussed it with @Derryrover. Using the wms_info__layer (_slug_ in the rasterlayer data model) is the only way to determine whether the layer belongs to a scenario. This field is also used in the API for the scenario__isnull filter. It is good for now.

**Comment by LirryPinter** [comment]
Minor comments:

- "Used storage" is too vague: lets do "Used storage (organization name)"

![image.png](https://images.zenhubusercontent.com/5edf4fb3573d27e45d88f233/349ace14-8ded-4f3a-9fce-2de06a76a3ce)

- This header is too thick because of the raw data column, can we put it in one line so that the header is the same size as all the other ones. 

![image.png](https://images.zenhubusercontent.com/5edf4fb3573d27e45d88f233/d1a78e6c-b147-4ab1-9e12-f74da02103d5)

- This is not a undo icon, but a reset icon. Can we use the undo icon I used in the design?

Other than that, great work! Looking noice

**Comment by lexvand** [comment]
I will create a new issue for the comments of Lirry, so that this issue can be closed.
