### ISSUE TITLE
Email field (validation?) becomes very slow when entry goes above 30 characters

### ISSUE THREAD

**Issue by lexvand** [nens/lizard-management-client#694]
I guess this has something to do with the field validation. When I type my email address it becomes very slow after passing 30 characters ...@nelen-schuurma.....

Can we somehow improve this?

**Comment by hoanphungt** [comment]
Correct! something goes wrong with the regex expression used to validate email address. According to this: https://stackoverflow.com/questions/29551388/performance-issue-while-evaluating-email-address-with-a-regular-expression, the ? in the expression caused the catastrophic backtracking issue. I removed the ? in the expression and the issue is resolved.
