### ISSUE TITLE
Name fields have max length of 30

### ISSUE THREAD

**Issue by lexvand** [nens/lizard-management-client#696]
Ca we add field validation to first and last name in Contacts form. Max_length is 30 according to the API response.

**Comment by hoanphungt** [comment]
Correct! something goes wrong with the regex expression used to validate email address. According to this: https://stackoverflow.com/questions/29551388/performance-issue-while-evaluating-email-address-with-a-regular-expression, the `?` in the expression caused the catastrophic backtracking issue. I removed the `?` in the expression and the issue is resolved.

**Comment by hoanphungt** [comment]
Merged in PR: https://github.com/nens/lizard-management-client/pull/699
