### ISSUE TITLE
Add delete action to all applicable forms

### ISSUE THREAD

**Issue by lexvand** [nens/lizard-management-client#697]
Following forms need to add the delete actions:

- [x] Alarm forms: raster alarm, timeseries alarm, group, contact, template
- [x] Personal API keys
- [x] Label
- [x] User
- [x] WMS layer
- [x] Raster source: needs to check for connected layers and label types
- [x] Raster layer
- [x] Timeseries
- [x] Monitoring network
- [x] Location: needs to check for connected timeseries

**Comment by hoanphungt** [comment]
@lexvand 
I propose to change this issue to **Add Delete action to all forms** as it is now inconsistent how some forms have the Action button with the delete action while some forms don't have it. I think it would take 1 point to add to all tables since the DeleteAction can now be reused quite easily.

**Comment by lexvand** [comment]
@hoanphungt Good suggestion. The forms that have exceptions are:
- Raster sources --> Delete action should show warning for related layers and labeltypes
- Same goes for location --> should do check for related timeseries (something we may not be dealing with yet in the location table?)
- Do not add to scenario raster layers form (deletion through scenario results)

**Comment by hoanphungt** [comment]
Added check for related timeseries when deleting location from both table and form
