### ISSUE TITLE
Timeseries table location ellipsis as in design

### ISSUE THREAD

**Issue by Derryrover** [nens/lizard-management-client#737]
Make the ellipsis working as in the design here:
https://xd.adobe.com/view/64bdf742-fee5-4907-a0f1-e9f27ecac3fc-31ee/screen/57ac9dda-b7c3-41de-9ada-65f3793ac1b5/

Had some difficulties with this one so made a separate ticket

**Comment by hoanphungt** [comment]
@Derryrover 
I investigated the current situation and IMO, the current situation is better than the design. Reasons:

- the current situation is the location field will be wrapped into multiple lines if too long while still display the full location name (and location code if name and code are different from each other). This gives sufficient information of the location. This will introduce the scrollbar in the table but with the recent fix of the table header and table body not aligned with each other when a scrollbar appears, the table is still very neat to view.

- The design one have the location name ellipsis while the the code is put into brackets, all in one single line. This solution would still be not enough because in many cases, the location code by itself can be long enough that one line is still not enough to display the information.

So I will close this issue as the current situation is already working well and IMO is better than the one in the design.
