### ISSUE TITLE
Alarm forms - Different behavior between adding thresholds and adding recipients

### ISSUE THREAD

**Issue by lexvand** [nens/lizard-management-client#752]
"Add threshold" button confirms the addition of an entry, "Add recipient" adds another line for filling in a new entry.

This is very counterintuitive and tricks the user into making mistakes. This should be made consistent.

**Comment by LirryPinter** [comment]
@Derryrover @lexvand @hoanphungt 

Hi guys,

Good point, can we start the form like this then:
![image.png](https://images.zenhubusercontent.com/5edf4fb3573d27e45d88f233/d22868be-2d48-4fce-9e69-157f8d9f6682)

(with the difference that the add recipient button is also grey so that it works the same as adding a threshold?

**Comment by hoanphungt** [comment]
@LirryPinter 
Hi Lirry,

I fixed the recipient field a little bit to make it behave more similarly to the threshold field by:

- Make the add recipient button work the same as the add threshold button when inactive/active
- You have to select a group and a template message before you can use the add recipient button to add it to the list

I temporarily deployed this to staging so you can have a look. Please let me know what you think.

**Comment by hoanphungt** [comment]
Lirry thinks the changes are good

**Comment by lexvand** [comment]
I agree. It looks much more consistent now.
