### ISSUE TITLE
Timeseries alarm form - Show timeseries parameter in dropdown

### ISSUE THREAD

**Issue by lexvand** [nens/lizard-management-client#755]
Currently in the timeseries dropdown the timeseries name and UUID are presented. The name is in most cases not very informative. It's better to replace it with "{parameter} ({unit})".

![image](https://user-images.githubusercontent.com/5370809/112678912-d3251600-8e6b-11eb-96fa-07cc6d08c2e5.png)

**Comment by hoanphungt** [comment]
@lexvand 
The problem with this approach is that in the timeseries endpoint: https://nxt3.staging.lizard.net/api/v4/timeseries/0bb67460-1870-417e-afa2-84d90e1ab492/, it does not contain information about the timeseries parameter and unit. 

It is possible to show the parameter and unit in the dropdown though since parameter and unit are included in the API response: https://nxt3.staging.lizard.net/api/v3/groundwaterstations/17941/?page_size=1000. 

However, it will create inconsistency in the data shown. For example, you create a new timeseries alarm and select from the dropdown a timeseries: `Stijghoogte (handmeting) (mm)` and later on, when you open the timeseries alarm form, you don't see that name anymore but only the name of the timeseries: `WNS9040.hand`.

What do you think?

**Comment by hoanphungt** [comment]
EDIT: timeseries `parameter` and `unit` can still be found under `observation_type` in the timeseries endpoint.
