### ISSUE TITLE
Continue location form 

### ISSUE THREAD

**Issue by Derryrover** [nens/lizard-management-client#770]
Proceed from here:
https://github.com/nens/lizard-management-client/issues/658

**Comment by hoanphungt** [comment]
@Derryrover Hi Tom,

Would it be a good idea if I pick up the location form from here?

**Comment by Derryrover** [comment]
@hoanphungt 
Yes is good

**Comment by hoanphungt** [comment]
@lexvand is it possible to have a location without geometry? I saw that the geometry field is not required in the API and can be null. Not sure if it is required in the location form though.

**Comment by lexvand** [comment]
@hoanphungt
Yes, geometry can be null. This is because of one of the main import formats that doesn't include this information.

For creating a new location in the form it would be preferable to make the geometry a required attribute. If this conflicts with the editing mode then make it optional in both forms for creating new and editing.

Can you work with this?

**Comment by hoanphungt** [comment]
@lexvand 
I made this an optional field for now. If we want this field to be required when creating a new location, this can also be easily done.

Regarding Tom's concern about an existing location can have a different geometry from its related asset, what is your opinion about it? I don't cover this case yet and read only the geometry information coming directly from the location endpoint. I think if this is the case then it is more like a backend problem. So the question is do we want the front-end to also cover this case and whether this issue is known by the back-end?

**Comment by hoanphungt** [comment]
@Derryrover 
Hi Tom,

Could you review this PR: https://github.com/nens/lizard-management-client/pull/785/? The field to select asset type is also added into the form. I added some comments in the PR as well.

Kr, Hoan

**Comment by Derryrover** [comment]
@hoanphungt 

Hi Hoan,
The ticket for the bug that made us decide to not add the json field in the location form is here:
https://github.com/nens/lizard-nxt/issues/4944
I think I forgot to link it to this ticket
kr Tom

**Comment by Derryrover** [comment]
@hoanphungt 

Yes looks good.
You can merge!

kr Tom
