### ISSUE TITLE
Overview of pending invitations

### ISSUE THREAD

**Issue by lexvand** [nens/lizard-management-client#835]
Managers can invite users to create a Lizard account. We should include an overview of pending invitations in the management interface.

**Comment by lexvand** [comment]
@LirryPinter Can you have a look at what's on staging right now and determine where you would like to include this feature?

**Comment by LirryPinter** [comment]
@lexvand 

This fits perfectly to usermanagement (since this is also to place only managers can go)

**Comment by lexvand** [comment]
@LirryPinter Yes, but where in the design? I guess we can make a simple modal for this to open with a button in the User table.

Or should it have its own environment (Invitations next to Users)? Managers should also be able to withdraw an invitation.

**Comment by LirryPinter** [comment]
@Derryrover @hoanphungt @lexvand 

I made some screenshots, since im reusing components that are already made.

![Group 257.png](https://images.zenhubusercontent.com/5edf4fb3573d27e45d88f233/9f8f4240-ccf2-49d7-a563-78e4f58665cf)

If there is no pending invitations we use the blocked/inactive button

![Group 256.png](https://images.zenhubusercontent.com/5edf4fb3573d27e45d88f233/ff441280-5205-4bac-b6b8-327e70e0f70f)

If there are pending ones the buttons lights up, when the user clicks it the modal will open

![Group 258.png](https://images.zenhubusercontent.com/5edf4fb3573d27e45d88f233/63a0fac3-cbd6-40bf-ab57-4e98707d171c)

I reused a small version of the list view. Right now people can delete (or cancel) their invitation. In the future we could also add 'resending invitation', that is why I kept the actions instead of making a custom delete column.

Note: please rename the 'new item' button to 'new user' so we have consistency

**Comment by lexvand** [comment]
@hoanphungt Any questions about Lirry's input?

The filtering on organisation (see related issue) will come soon. Can be applied once it's available on staging. For now just show all pending invitations a manager can see (unlikely that external users are manager in multiple organisations).

**Comment by lexvand** [comment]
Pending invitations that are older than 15 days are cleaned up automatically. So 15 days can be used as a timedelta to determine the expiration date.

**Comment by hoanphungt** [comment]
@lexvand @LirryPinter 
Looks good! 

Initially, I was thinking of making a separate tile for the list of pending invitations next to the user tile. It would actually be very simple to make and can be easily developed further if we want to add new features to it compared to using a modal as in the design (e.g. search bar, creating new invitation, invitation form ...). 

I do see the benefit of the modal in the user table though as manager can easily see the list of pending invitation at a glance instead of going back and forth to go to the invitation list.

What do you two think about it?

**Comment by Lirry18** [comment]
@hoanphungt @lexvand 

I also thought about a separate tile, but I think that can be a bit of overkill for the user. Can not really imagine that there is ever more than 3 pending invitations at the same time, so a search bar wouldn't be necessary. Also, creating a new invitation is the same as creating a new user, and an invitation form can't really be modified.

I would say the modal is easier for the user and more natural :)

@lexvand what do you think?

**Comment by lexvand** [comment]
I agree. There will be cases of longer lists of pending invitations, especially when a new organisation is introduced. But I don't expect we need to paginate the results to keep it usable for managers. And according to the data model indeed an invitation is nothing more than a new user, so it is logical to include it in the User management.

**Comment by hoanphungt** [comment]
Let's make it a modal in the user management page then :)

**Comment by hoanphungt** [comment]
@Derryrover 
Hi Tom,

Could you review this PR: https://github.com/nens/lizard-management-client/pull/840/?

Kr, Hoan

**Comment by Derryrover** [comment]
@hoanphungt 

Hi Hoan,

Looks and works good!
Ready to merge, but I also left 2 comments that you can think about.

kr Tom
