### ISSUE TITLE
2 small issues: tile hoover over + user invite revoke instead of cancel

### ISSUE THREAD

**Issue by Derryrover** [nens/lizard-management-client#846]
2 points of feedback from Daan:

- Should we give the tiles a hover color ?
- should cancelling user invite be called 'revoke' instead of 'cancel'.

**Comment by Derryrover** [comment]
@LirryPinter 
@daanvaningen 

Hi Lirry,

Hope you feel better.
2 feedback points from Daan.
If you agree ( and pick the hover color) we can implement this.
Thanks in advance

kr Tom

**Comment by daanvaningen** [comment]
My thoughts about it:
- The tiles look a bit flat due to them having the same background color as
the canvas. So a slightly different background color and maybe some kind
over hover effect will pop them out a bit.
- I thought clicking on the 3 dots next to the pending invite, and then
seeing 'cancel' was a bit weird, like there wasn't any action to perform. I
think changing this to 'revoke' (or something else) might be a bit more
descriptive.

Op di 1 jun. 2021 om 16:18 schreef Tom de Boer ***@***.***>:

**Comment by LirryPinter** [comment]
@daanvaningen @Derryrover 

In the original design the tiles looked a bit different and had a hover animation (making them a fraction larger) please see an example here: https://xd.adobe.com/view/a24de82c-bb9a-4ebd-bc9b-6fb448a06e1f-f71e/ 

Just hover over the tiles and how you like that!

I am fine with "revoke" instead of cancel!

**Comment by daanvaningen** [comment]
Those tiles look perfect to me :)

Op ma 7 jun. 2021 om 14:31 schreef LirryPinter ***@***.***>:

**Comment by hoanphungt** [comment]
Also added a small animation when hover over the back arrow in the table and the form as in the design.

**Comment by hoanphungt** [comment]
@LirryPinter @daanvaningen 
I added the animation for the app tiles and put it on staging. Would you like to check and let me know what you think?

**Comment by LirryPinter** [comment]
@hoanphungt @daanvaningen 

Looks awesome! great work

**Comment by daanvaningen** [comment]
looks great!
