### ISSUE TITLE
Evaluate usage of page_size=0 or page_size=10000

### ISSUE THREAD

**Issue by Derryrover** [nens/lizard-management-client#859]
For each of these places find out if:

- We should better use pagination
- If not, in case of page_size=0 we should rateher use page_size=10000 (because the api response from page_size=0 is deviant)

For some cases it might be okey to use page_size=10000 if:
- we can be sure that the maximal items returned will rarely be that big?
- the usage is that we retrieve all possible items?

**Comment by hoanphungt** [comment]
**Places with page_size=0:**

action.js - fetchOrganisations:
- `/api/v4/users/${userId}/organisations/?page_size=0`
- `/api/v4/organisations/?page_size=0`

action.js - fetchObservationTypes:
- `/api/v4/observationtypes/?page_size=0`

raster.ts - listTemporalRastersContainingV3:
- `/api/v3/rasters/?page_size=0&name__icontains=${searchString}&temporal=true`

LocationForm.tsx - useEffect:
- `/api/v4/timeseries/?page_size=0&location__uuid={uuid}`

LocationTable.tsx - useEffect:
- `/api/v4/timeseries/?page_size=0&location__uuid={uuid}`

UserTable.tsx - useEffect:
- `/api/v4/invitations/?page_size=0&status=pending`

**Places with page_size=1000 or more**

action.js - fetchColormap:
- `/api/v3/colormaps/?format=json&page_size=100000`

GroupForm.tsx - useEffect:
- `/api/v4/contacts/?page_size=1000&organisation__uuid={uuid}`

AddToGroupModal.tsx - useEffect:
- `/api/v4/contactgroups/?page_size=1000&organisation__uuid={uuid}`

AddToMonitoringNetworkModal.tsx - useEffect:
- `/api/v4/monitoringnetworks/?page_size=1000&organisation__uuid={uuid}`

Recipients.tsx - useEffect:
- `/api/v4/contactgroups/?organisation__uuid=${uuid}&page_size=1000`
- `/api/v4/messages/?organisation__uuid=${uuid}&page_size=1000`

TimeseriesSelection.tsx - SelectDropdown of locations:
-`/api/v3/{asset_name}s/{asset_id}/?page_size=1000`

**Comment by hoanphungt** [comment]
@lexvand @Derryrover @byrman 
I made a list of api calls that are using page_size=0 or page_size=1000 in the management client in the comment above. 

My question is in case we know for sure that the results of an endpoint are not a lot (hundreds or less than 1000 - for example: contacts, invitations, contact groups, templates, monitoring networks ...), would it be ok to retrieve them all at once using `page_size=0`? And between `page_size=0` and `page_size=1000`, which one do you prefer? I personally prefer to use `page_size=0` because I know that this query will return me all the available data directly in the response.

**Comment by hoanphungt** [comment]
@Derryrover 
Hi Tom,

As mentioned above, although I have been able to eliminate the page_size=0 or 1000 in some of the places (for example: observation types, suppliers and colormaps), there are still quite many of them left (11). However, they typically give very small response of much less than 100 results except from the fetch for organisations.

I am thinking of 2 approaches from here:

1. To build a hook component for the fetching that has its own fetching state and it will build the data one by one based on the `next` parameter from the request's response. This component can then be reused in different places.

2. To specifically solve the case with organisations only and leave everything intact (with either using page_size=0 or page_size=1000 for consistency) since we know that the other ones give relatively small response anyway.

Let me know what you think or we can discuss it further.

**Comment by hoanphungt** [comment]
@Derryrover 
Hi Tom,

Could you review the PR: https://github.com/nens/lizard-management-client/pull/873/?

Kr, Hoan

**Comment by Derryrover** [comment]
@hoanphungt 

Hi Hoan,

Ready to merge

I think the code looks good.
I tested the user/organisation ones in the actions.js file and it works well
I also tested to usePagination hooks and they also work correct.
I didnot test everything, but I think it all will work.

kr Tom

**Comment by lexvand** [comment]
I went through the list of changes. Not all changes have a use case in which pagination is required (small amount of results). But all methods turned out to be testable in some place in the client, so I'm confident that it would work correctly when datasets grow to multiple pages in other places.

The only minor performance issues I ran into happened when fetching organisations at initialisation of the app. For my user account it takes a little bit longer to load due to the 10 sequential requests it has to do. But this is handled correctly by showing a spinner and it will not happen for actual users, because they have way less organisation roles. One time the third request took 6 seconds, probably because the API was temporarily less responsive. This could of course also happen when retrieving all organisations at once.
