### ISSUE TITLE
Management client doesn't open correctly when entering URL

### ISSUE THREAD

**Issue by lexvand** [nens/lizard-management-client#910]
Issues:
- https://nxt3.staging.lizard.net/management gives a 404
- https://nxt3.staging.lizard.net/management/ does open the management page, but without tiles
- https://nxt3.staging.lizard.net/management/data_management/ and all other sub pages also give a 404

This way we can't link to management from other locations correctly.

**Comment by Derryrover** [comment]
Ninx issues repaired as part of ticket:
https://app.zenhub.com/workspaces/team-lizard-5ef307a0fac67c0022166258/issues/nens/lizard-nxt/5161

The lizard-management internal routing "https://nxt3.staging.lizard.net/management/ does open the management page, but without tiles" fixed in feature branch "tom-landing_page".

**Comment by lexvand** [comment]
Tested on staging:
- Clicking through all pages including the home page gives no problems
- Refreshing any of the pages goes well
- Entering the URL of sub pages works well
- All URL's work both with and without closing `/`

All good!
